# Generated by Django 3.2.6 on 2022-07-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=20, unique=True)),
                ('create_date', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('opinion', models.CharField(blank=True, max_length=10, null=True)),
                ('writer', models.CharField(max_length=20)),
                ('stock_firm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_opinion', models.CharField(max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.report')),
            ],
        ),
    ]
