# Generated by Django 4.0.3 on 2022-07-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('subject', models.CharField(max_length=200)),
                ('opinion_buy', models.TextField()),
                ('opinion_sell', models.TextField()),
                ('opinion_hold', models.TextField()),
                ('writer', models.CharField(max_length=50)),
                ('stock_firm', models.CharField(max_length=50)),
                ('pdf_file', models.FilePathField()),
            ],
        ),
    ]
