# Generated by Django 4.0.3 on 2022-07-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AInalyst', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columns',
            old_name='opinion_buy',
            new_name='chart',
        ),
        migrations.RenameField(
            model_name='columns',
            old_name='opinion_hold',
            new_name='company_inf',
        ),
        migrations.RenameField(
            model_name='columns',
            old_name='opinion_sell',
            new_name='opinion',
        ),
        migrations.AlterField(
            model_name='columns',
            name='pdf_file',
            field=models.TextField(),
        ),
    ]
