# Generated by Django 4.0.3 on 2022-07-07 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AInalyst', '0002_rename_opinion_buy_columns_chart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
