# Generated by Django 4.0.3 on 2022-07-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AInalyst', '0003_columns_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='fair_price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
