# Generated by Django 3.2.6 on 2022-08-01 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('company', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('article', models.TextField(blank=True, null=True)),
                ('opinion', models.CharField(blank=True, max_length=20, null=True)),
                ('stock_firm', models.CharField(max_length=20)),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_opinion', models.CharField(max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.report')),
            ],
        ),
    ]
