# Generated by Django 3.2.6 on 2022-08-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('article', models.TextField(blank=True, null=True)),
                ('opinion', models.CharField(blank=True, max_length=20, null=True)),
                ('new_opinion', models.CharField(blank=True, max_length=20, null=True)),
                ('firm', models.CharField(max_length=20)),
            ],
        ),
    ]
