# Generated by Django 3.2.6 on 2022-07-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inference',
            name='new_opinion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='opinion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
